# Generated by Django 6.0.2 on 2026-03-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_Partner_Finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='FYP_Partner_Finder.appuser'),
            preserve_default=False,
        ),
    ]
