# Generated by Django 6.0.1 on 2026-05-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_Partner_Finder', '0002_team_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_size',
            new_name='available_team_size',
        ),
    ]
