# Generated by refactor to Django auth.User

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.hashers import make_password


def copy_appuser_to_auth_user_and_remap_fks(apps, schema_editor):
    AppUser = apps.get_model("FYP_Partner_Finder", "AppUser")
    User = apps.get_model("auth", "User")

    UserProfile = apps.get_model("FYP_Partner_Finder", "UserProfile")
    Skill = apps.get_model("FYP_Partner_Finder", "Skill")
    Experience = apps.get_model("FYP_Partner_Finder", "Experience")
    Conversation = apps.get_model("FYP_Partner_Finder", "Conversation")
    Message = apps.get_model("FYP_Partner_Finder", "Message")

    existing_users = list(User.objects.all())
    existing_by_id = {u.id: u for u in existing_users}
    existing_by_username = {u.username: u for u in existing_users if u.username}
    existing_by_email = {u.email: u for u in existing_users if getattr(u, "email", "")}

    id_map = {}

    for au in AppUser.objects.all().order_by("id").iterator():
        candidate = existing_by_id.get(au.id)
        if candidate and candidate.username == au.username and candidate.email == au.email:
            id_map[au.id] = candidate.id
            continue

        candidate = existing_by_username.get(au.username)
        if not candidate and au.email:
            candidate = existing_by_email.get(au.email)
        if candidate:
            id_map[au.id] = candidate.id
            continue

        if au.id not in existing_by_id:
            user = User(id=au.id, username=au.username, email=au.email or "")
        else:
            user = User(username=au.username, email=au.email or "")
        user.password = make_password(None)
        user.save()

        existing_by_id[user.id] = user
        if user.username:
            existing_by_username[user.username] = user
        if getattr(user, "email", ""):
            existing_by_email[user.email] = user

        id_map[au.id] = user.id

    for old_id, new_id in id_map.items():
        if old_id == new_id:
            continue
        UserProfile.objects.filter(user_id=old_id).update(user_id=new_id)
        Skill.objects.filter(user_id=old_id).update(user_id=new_id)
        Experience.objects.filter(user_id=old_id).update(user_id=new_id)
        Conversation.objects.filter(user1_id=old_id).update(user1_id=new_id)
        Conversation.objects.filter(user2_id=old_id).update(user2_id=new_id)
        Message.objects.filter(sender_id=old_id).update(sender_id=new_id)
        Message.objects.filter(receiver_id=old_id).update(receiver_id=new_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("FYP_Partner_Finder", "0002_message_receiver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(copy_appuser_to_auth_user_and_remap_fks, noop_reverse),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="AppUser"),
    ]

