# Generated by Django 6.0.1 on 2026-05-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_Partner_Finder', '0003_rename_team_size_team_available_team_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='passing_year',
        ),
    ]
