# Generated by Django 6.0.1 on 2026-05-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_Partner_Finder', '0004_remove_userprofile_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(),
        ),
    ]
