# Generated by Django 6.0.1 on 2026-05-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_Partner_Finder', '0005_alter_userprofile_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='req_role',
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='FYP_Partner_Finder.team')),
            ],
        ),
    ]
