# Generated by Django 6.0.1 on 2026-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_Partner_Finder', '0006_remove_team_req_role_teamrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_description',
            field=models.TextField(default=''),
        ),
    ]
