# Generated by Django 6.0.1 on 2026-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_Partner_Finder', '0010_remove_userprofile_about_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(max_length=20),
        ),
    ]
